name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bloc
  flutter_bloc: ^6.1.1

  # Database
  moor: ^3.4.0
  path: ^1.7.0
  path_provider: ^1.6.24
  sqlite3_flutter_libs: ^0.3.0

  # Util
  equatable: ^1.2.5

dev_dependencies:
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  moor_generator: ^3.4.0

  # Test
  mockito: ^4.1.2
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
